//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPA_Mech.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bez1Entities : DbContext
    {
        public Bez1Entities()
            : base("name=Bez1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<NaryadList> NaryadList { get; set; }
        public virtual DbSet<Oboruds> Oboruds { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<TableTest> TableTest { get; set; }
        public virtual DbSet<TableTest2> TableTest2 { get; set; }
        public virtual DbSet<TechKart> TechKart { get; set; }
        public virtual DbSet<UMRK_BR> UMRK_BR { get; set; }
        public virtual DbSet<UMRK_ISP> UMRK_ISP { get; set; }
        public virtual DbSet<UMRK_OP> UMRK_OP { get; set; }
        public virtual DbSet<UMRK_OP_TK> UMRK_OP_TK { get; set; }
        public virtual DbSet<UMRK_PPR> UMRK_PPR { get; set; }
        public virtual DbSet<UMRK_REM> UMRK_REM { get; set; }
        public virtual DbSet<UMRK_SM> UMRK_SM { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
