//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPA_Mech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaryadList
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Nar_vidal { get; set; }
        public Nullable<int> Smena { get; set; }
        public Nullable<int> Smena_long { get; set; }
        public string Master { get; set; }
        public string FIO { get; set; }
        public string Post { get; set; }
        public string Podrazd { get; set; }
        public string Oborud { get; set; }
        public string TO_Type { get; set; }
        public string Work_list { get; set; }
        public Nullable<int> Time_Plan { get; set; }
        public Nullable<int> Time_Fakt { get; set; }
        public string StatusNar { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Brigada { get; set; }
    }
}
