//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPA_Mech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oboruds
    {
        public int id { get; set; }
        public string Podrazd { get; set; }
        public string NameOborud { get; set; }
        public string Uchastok { get; set; }
        public string typeTo { get; set; }
    }
}
