//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPA_Mech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableTest2
    {
        public int Id { get; set; }
        public string Name2 { get; set; }
        public string idT { get; set; }
    }
}
