//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPA_Mech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechKart
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string TypeOborud { get; set; }
        public string Состав_работ { get; set; }
        public string КР { get; set; }
        public string КРу { get; set; }
        public string ТО { get; set; }
        public string Т { get; set; }
        public string ЕО { get; set; }
        public string А { get; set; }
        public string М { get; set; }
    }
}
