//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPA_Mech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMRK_REM
    {
        public int Id_rem { get; set; }
        public int Num_br { get; set; }
        public int sm { get; set; }
        public string Podrazd { get; set; }
        public string Oborud { get; set; }
        public string Type_Oborud { get; set; }
        public string Type_work { get; set; }
        public Nullable<bool> ind { get; set; }
        public Nullable<System.DateTime> NR { get; set; }
        public Nullable<System.DateTime> KR { get; set; }
        public Nullable<System.DateTime> TR { get; set; }
        public Nullable<System.DateTime> ND { get; set; }
        public Nullable<System.DateTime> KD { get; set; }
        public Nullable<System.DateTime> TD { get; set; }
        public string Komment { get; set; }
        public string Komment1 { get; set; }
        public Nullable<int> Pr_rem { get; set; }
    }
}
