//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPA_Mech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMRK_BR
    {
        public int Id_br { get; set; }
        public int sm { get; set; }
        public Nullable<int> Num_br { get; set; }
        public string Tab { get; set; }
        public string FIO { get; set; }
        public string Prof { get; set; }
        public string Org { get; set; }
        public byte[] Rowversion { get; set; }
    }
}
