//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPA_Mech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMRK_OP_TK
    {
        public int Id_oper_tk { get; set; }
        public bool Used { get; set; }
        public string Operation { get; set; }
        public string Oborud { get; set; }
        public Nullable<int> Pro1 { get; set; }
        public Nullable<int> Pro2 { get; set; }
        public Nullable<int> Pro3 { get; set; }
        public Nullable<int> Pro4 { get; set; }
        public Nullable<int> Pro5 { get; set; }
        public Nullable<int> Pro6 { get; set; }
        public Nullable<int> Pro7 { get; set; }
        public Nullable<int> Pro8 { get; set; }
        public Nullable<int> Pro9 { get; set; }
        public Nullable<int> Pro10 { get; set; }
        public Nullable<int> Pro11 { get; set; }
        public Nullable<int> Pro12 { get; set; }
        public Nullable<int> Pro13 { get; set; }
        public Nullable<int> Pro14 { get; set; }
        public Nullable<int> Pro15 { get; set; }
        public Nullable<System.DateTime> T1 { get; set; }
        public Nullable<System.DateTime> T2 { get; set; }
        public Nullable<System.DateTime> T3 { get; set; }
        public Nullable<System.DateTime> T4 { get; set; }
        public Nullable<System.DateTime> T5 { get; set; }
        public Nullable<System.DateTime> T6 { get; set; }
        public Nullable<System.DateTime> T7 { get; set; }
        public Nullable<System.DateTime> T8 { get; set; }
        public Nullable<System.DateTime> T9 { get; set; }
        public Nullable<System.DateTime> T10 { get; set; }
        public Nullable<System.DateTime> TR1 { get; set; }
        public Nullable<System.DateTime> TR2 { get; set; }
        public Nullable<System.DateTime> TR3 { get; set; }
        public Nullable<System.DateTime> TR4 { get; set; }
        public Nullable<System.DateTime> TR5 { get; set; }
        public Nullable<System.DateTime> TR6 { get; set; }
        public Nullable<System.DateTime> TR7 { get; set; }
        public Nullable<System.DateTime> TR8 { get; set; }
        public Nullable<System.DateTime> TR9 { get; set; }
        public Nullable<System.DateTime> TR10 { get; set; }
        public string Prisp { get; set; }
        public string Material { get; set; }
        public string TB { get; set; }
        public string Komment { get; set; }
        public string Username { get; set; }
        public byte[] Rowversion { get; set; }
    }
}
