//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPA_Mech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMRK_SM
    {
        public int Id_sm { get; set; }
        public System.DateTime Date_nar { get; set; }
        public int Num_sm { get; set; }
        public int Prod { get; set; }
        public string Nar_vid { get; set; }
    }
}
