//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPA_Mech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMRK_OP
    {
        public int Id_oper { get; set; }
        public string Operation { get; set; }
        public Nullable<int> Oper_tk_fk { get; set; }
        public int Id_rem { get; set; }
        public Nullable<int> isp { get; set; }
        public Nullable<System.DateTime> time_op { get; set; }
        public Nullable<bool> Regl { get; set; }
    }
}
